### PR TITLE
Corelogpub

### PR DESCRIPTION
**Pull request by KevinPhemius**
First implementation of the LogPub.
Defined as a new module in the core.
The core.connectivity module sends _all_ messages (from the shim and the backend) to an interprocess queue (ipc). LogPub pull the message and put them in a PUB queue for the tool(s) to consume.

Please check the dependancies in the xml, I'm new to OGSi

### CODE REVIEW

**Comment by TimVinkemeier** [comment]
Hi Kevin,

I'm sorry, but I have a few problems with your approach:
- You modify the ZeroMQBasedConnector. Don't do that, it is supposed to **only** handle incoming and outgoing data, no logic.
- You introduce another thread. This is not a huge issue, but the thread is unnecessary (I think), since you don't want to receive any messages (I will get to that).
- You use ipc:// transport. As stated [here](https://github.com/zeromq/jeromq/blob/master/README.md), JeroMQ only supports that if the endpoint also uses JeroMQ. Can you guarantee that? I would suggest you just switch to TCP, it barely makes a difference and is easily compatible.

Having said that, here is a better approach:
- Clean the added code from the ZeroMQConnector.
- Let the LogPub implement and publish (via Blueprint) the interfaces IShimMessageListener and IBackendMessageListener. That way you will automatically be called when messages arrive and don't need the additional control channel.
- Include a blueprint.xml file in your resources (have a look at the other modules for details) to instantiate the LogPub module and publish the services.

I hope this helps, feel free to ask me, if you have any questions :wink: 

Best,
Tim

**Comment by TimVinkemeier** [comment]
We could also think about if it is a good approach to have the module in the same project (since I am working on the basic core modules and you would be working on the LogPub) or if we should keep them separate (and see the LogPub as a core plugin).

**Comment by TimVinkemeier** [comment]
One more thing I just saw: Make sure that you have the Osmorc plugin for IntelliJ installed. It handles the generation of the Manifest.MF file. You don't seem to have it, because the relevant parts are missing in the .iml files...

**Comment by KevinPhemius** [comment]
Hi Tim,

as I understood from the discussions the LogPub would be a core plugin.

The LogPub will eventually have to receive messages (from the tools). It's a planned feature so I though that making it a thread right now would be easier.

**Comment by KevinPhemius** [comment]
Ok for leaving the ZeroMQConnector alone. I will do your approach instead.

**Comment by TimVinkemeier** [comment]
Okay, well then you can leave the thread but use the control channel only for STOP_COMMAND or message relay, like the other bundles do it.

**Comment by TimVinkemeier** [comment]
I am just adding a IManagementMessageListener, so you will also be able to capture them, if you wish so (next commit will include that).

**Comment by KevinPhemius** [comment]
Hello,

what does this code do (same for the shim): 

<pre>
backendListener.OnDataReceived(data, senderId);
</pre>

does it call the SendData method from the thread?

**Comment by TimVinkemeier** [comment]
I don't understand the question... It calls the OnDataReceived method on whatever listener is registered. In this case, the listener is the ShimManager (or the BackendManager, respectively). This is configured in the blueprint.xml file.

**Comment by KevinPhemius** [comment]
Yes, I confused myself...
Thanks.

**Comment by KevinPhemius** [comment]
The changes are done.
I hope the implementation/publication/blueprint part is OK.

-- Kévin

**Comment by TimVinkemeier** [comment]
Hi,

that was fast, however, there still are some issues:
- You implemented `IShimMessageListener` and `IBackendMessageListener`, but in their methods you directly use the PUB socket, which lives in another thread. This is not supported, you should take the extra turn via the control socket.
- You can use `message.ToByteRepresentation()` to get the whole message (including the header) as a byte[].
- In the blueprint, `reference-list` means a service _import_. You however have to _export_ them like so:

``` xml
<service ref="logPub"
             interface="eu.netide.core.api.IShimMessageListener"/>
<service ref="logPub"
             interface="eu.netide.core.api.IBackendMessageListener"/>
```
- In the `pom.xml` you specify that you have a dependency on `eu.netide.core.connectivity` (In the `<Import-Package>` part). However, this is not the case, so you should remove the dependency.

And just a small improvement that I am just adding to the other bundles: I am moving from using `System.out.println()` to a proper logging mechanism provided by Karaf. Add the following dependency to the `pom.xml` file and use the logger as follows:

``` xml
<dependency>
  <groupId>org.slf4j</groupId>
  <artifactId>slf4j-api</artifactId>
  <version>1.7.12</version>
  <scope>provided</scope>
</dependency>
```

Also add `org.slf4j` to the `<Import-Package>` part in your `pom.xml`, since the bundle is provided by Karaf.

Usage:

``` java
// somewhere at the beginning of your class, substitute LogPub.class if necessary
private static final Logger logger = LoggerFactory.getLogger(LogPub.class);

// usage instead of System.out.println()
logger.info("some message here");

// logging an exception
logger.error("description", exception);
```

If you have any questions, feel free to ask.
Best,
Tim

**Comment by KevinPhemius** [comment]
Hello,
- Ok, I get how to use the control socket to get the messages to the thread (and the PUB socket). Much clearer now. Thanks.
- Yes, I do not have a dependency on core.connectivity anymore. I fixed the blueprint and the pom.xml to export the services.
- I switched to the slf4j logger. Is it also necessary in the test class? 

Best,
Kévin

**Comment by TimVinkemeier** [comment]
Hi,
- You can use the logger in the test, but it does not really make a difference there.
- You have to remove the `reference-list` parts from the `blueprint.xml`, since you don't use them.
- Interestingly, since you are only publishing messages currently, you would not need the additional thread at all :laughing: It is however fine to just leave it like this.
- Did you test the bundle installed in Karaf? Did you also test the PUB socket with a client (e.g. using a Python script)?

Best,
Tim

**Comment by TimVinkemeier** [comment]
@KevinPhemius Is this branch now ready for merging? It would be nice to be able to test the LogPub and Andrés @andres-beato needs it to develop the debugger...

**Comment by KevinPhemius** [comment]
I sent a message to Elisa and Andrés about testing the LogPub with the new shims/BE.
I think they already planned to do it if I read a previous email correctly.
Otherwise I would have to do it when I return from vacation next Tuesday.

Best,

Kévin

On Sep 3, 2015 09:42, Tim Vinkemeier notifications@github.com wrote:
@KevinPhemius Is this branch now ready for merging? It would be nice to be able to test the LogPub and Andrés @andres-beato needs it to develop the debugger...

---

**Comment by TimVinkemeier** [comment]
@ElisaRojas @andres-beato Have you done that already?

**Comment by ElisaRojas** [comment]
@KevinPhemius:
Sorry, but I was back from holidays just two days ago ;) @andres-beato (back just a few days before as well) has already tried your project and saw the logpub loaded. His current idea is to modify the current debugger and once he sees the debbugger is correctly connected, he will test it with the dummy Java client that Tim prepared (because currently there are no real migrated backends or shims to test it). 
But, as far as I know, the merging could be done already (@andres-beato , correct me if I'm wrong).

**Comment by andres-beato** [comment]
Yes, you are right @ElisaRojas 
These are the next steps to test the logpub and I think the merging between CoreImplementation branch and CoreLogPub branch could be done already.

**Comment by TimVinkemeier** [comment]
Great, done :wink:

**Comment by KevinPhemius** [comment]
Additionally the LogPub only sends messages to the logger (well to a PUB queue).
When everything works correctly I will add the queue to get the messages _from_ the logger (the SUB).
But this is "next next" steps.

Best,

Kévin

On Sep 3, 2015 12:27 PM, andres-beato notifications@github.com wrote:
Yes, you are right @ElisaRojas
These are the next steps to test the logpub and I think the merging between CoreImplementation branch and CoreLogPub branch could be done already.

---

**Pull request merged**
